### ISSUE TITLE
Add general purpose input buffer

### ISSUE THREAD

**Issue by Pyxus** [Pyxus/fray#20]

**Comment by Remi123** [comment]
There is some games where pressing X does an action, but holding the X button does another while it's pressed. For example, rolling in Elden Ring is executed by pressing B , but holding B for a certain amount of time make you run instead, until B is released. Dispatching those kind of actions would be very useful, and I think adding an example would in the doc is a must since it touch at multiple ways of parameters.

**Comment by Pyxus** [comment]
> There is some games where pressing X does an action, but holding the X button does another while it's pressed. For example, rolling in Elden Ring is executed by pressing B , but holding B for a certain amount of time make you run instead, until B is released. Dispatching those kind of actions would be very useful, and I think adding an example would in the doc is a must since it touch at multiple ways of parameters.

Thank you for your suggestion. This is now being tracked here: #23
