### ISSUE TITLE
Errors on import and enable

### ISSUE THREAD

**Issue by 20milliliter** [Pyxus/fray#27]
Attempting to import or enable fray into Godot Ver. rc1 returns errors.

Assuming the cause is rc1 having made breaking changes to Fray—and the most simple fix being downgrading—what version was used for the development of PR #24?

**Comment by Pyxus** [comment]
I identified a minor mistake on my end. I referenced the `FrayInput` autoload before it was created, which caused a problem when importing the addon to a new project. I fixed this issue with my recent commit: b17fa56cbcfcc1a7a2604d4a033ffd01e8c74910

However, I believe the majority of the errors are due to a problem with rc1 that occurs when you try to import via drag and drop. If you instead import the addon through your file explorer, it seems to function properly.

Let me know if this fixes things on your end.

**Comment by 20milliliter** [comment]
That seems to do the trick, yes.
