### ISSUE TITLE
Add editor tools for easier project setup and configuration

### ISSUE THREAD

**Issue by ca3games** [Pyxus/fray#5]
Hi, this is a nice addon.
But I wasn't unable to use it on my game, needs a proper tutorial to implement a basic input buffer.
Also, a good thing eventually would be a nice GUI editor tab for the project to easily set up stuff.

cool project.

**Comment by Pyxus** [comment]
Hey, sorry for late reply didn't expect anyone to post an issue!
Completely agree and thanks for showing interest in the project. I'm pretty slow to make updates since I work on this in my free time but editor integration is definitely on my to-do list and may be my focus the next time I touch this.

**Comment by Pyxus** [comment]
Decided to close this for the foreseeable future. I have less time to work on the add-on compared to before and I believe good documentation and helper classes, like the builders I've written, make working with things programmatically easy enough.
