### ISSUE TITLE
Root state does not make it easy to interact with sub states

### ISSUE THREAD

**Issue by Pyxus** [Pyxus/fray#64]
Currently there is no easy way to reference sub states. The obvious solution to me is to use a path based system. So rather than `get_state(name_of_sub_state)` you'll use `get_state(path/to/state)`. It should be relatively simple to implement but considering the slow pace of development this can be put on hold for later.

**Comment by Remi123** [comment]
I didn't even know that it was possible to have sub states. How is it done ? Is it possible because FrayRootState can contains other FrayRootState or am I missing something? How is the transition from `State_A` to `State_B/SubState_A` handled ? 

I expect something like this where sub states are some kind of tree-like structure that you need to traverse. 

Something like this: 

`State_A` to `State_B/SubState_A`
1. State_A EXIT
2. State_B ENTER
3. State_B/SubState_A ENTER

And going back to State_A

`State_B/SubState_A` to `State_A`
1. State_B/SubState_A EXIT
2. State_B EXIT
3. State_A ENTER

**Comment by Pyxus** [comment]
> I didn't even know that it was possible to have sub states. How is it done ? Is it possible because FrayRootState can contains other FrayRootState or am I missing something?

You got it, that is correct. `FrayRootState` used to be called `FrayStateMachineState` for that reason. 

> I expect something like this where sub states are some kind of tree-like structure that you need to traverse.

Your description is how it *should* work. But admittedly while the structure is there it hasn't been adequately tested yet so it's possible there are issues in the order of events.
